FROM node:16-alpine

USER node
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]


# docker build -f Dockerfile.dev -t USERNAME:frontend .
# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/docker/lsn_04_frontendApp/frontend-app:/home/node/app USERNAME:frontend
# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/docker/lsn_04_frontendApp/frontend-app:/home/node/app 3c534410ca73 npm run test