version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - ~/docker/lsn_04_frontendApp/frontend-app:/home/node/app
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ~/docker/lsn_04_frontendApp/frontend-app:/home/node/app
    command: ["npm", "run", "test"]