name: test_and_deploy_docker_frontendapp
on:
  push:
    branches:
      - master

jobs:
  test:
    name: test_before_deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout_code
        uses: actions/checkout@v2
        
      - name: docker_login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: docker_build
        run: docker build -t youngermm/frontend-app -f ./Dockerfile.dev .

      - name: test_application
        run: docker run -e CI=true youngermm/frontend-app npm test